controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate
    containers:
      main:
        image:
          repository: farcasterxyz/hubble
          # you may want to use a specific version here
          tag: latest
          pullPolicy: Always
        # adapting docker-compose.yml from farcasterxyz/hub-monorepo/apps/hubble
        # command: ["npx", "pm2-runtime", "start", "pm2.config.cjs"]
        command: ['/bin/sh', '-c']
        args:
          - |
            set -e
            node build/cli.js identity create
            npx pm2-runtime start pm2.config.cjs
        #probes:
        #  liveness:
        #  readiness:

        # see https://github.com/farcasterxyz/hub-monorepo/blob/main/apps/hubble/docker-compose.yml#L20
        # make sure the statsd-metrics-server value is of the form:
        # releasename-statsd.namespace.svc.cluster.local
        # where releasename and namespace match your deployment
        # like for releasename hubble and namespace onchain:
        # hubble-statsd.onchain.svc.cluster.local
        # and don't forget to set the port! e.g. 8125

        # if boostrapping via node peer, pick from here: https://github.com/farcasterxyz/hub-monorepo/blob/main/apps/hubble/src/bootstrapPeers.mainnet.ts

        # base64 encoded identity file created via `yarn create identity`
        # CLI source code that contains this command: https://github.com/farcasterxyz/hub-monorepo/blob/main/apps/hubble/src/cli.ts
        # - name: IDENTITY_B64
        #   value: "TODO: base64 encoded identity file GENEATE as per README.md"
        env:
          - name: CATCHUP_SYNC_WITH_SNAPSHOT
            value: "true"
          - name: NODE_OPTIONS
            value: "--no-warnings --max-old-space-size=8192"
          - name: HUBBLE_ARGS
            value: >-
              start
              --ip 0.0.0.0
              --gossip-port 2282
              --rpc-port 2283
              --eth-mainnet-rpc-url https://rpc.ankr.com/eth
              --l2-rpc-url https://rpc.ankr.com/optimism
              --network 1
              --hub-operator-fid 16085
              --rpc-subscribe-per-ip-limit 4
              -b /dns/hoyt.farcaster.xyz/tcp/2282
              --statsd-metrics-server hubble-statsd.onchain.svc.cluster.local:8125
              --opt-out-diagnostics true
          - name: BOOTSTRAP_NODE
            value: "/dns/hoyt.farcaster.xyz/tcp/2282/"
        # resources:
        #   requests:
        #     memory: 16Gi


  statsd:
    type: deployment
    replicas: 1
    strategy: Recreate
    containers:
      main:
        image:
          repository: graphiteapp/graphite-statsd
          tag: 1.1.10-5

service:
  main:
    controller: main
    ports:
      http:
        port: 2281
      gossip:
        enabled: true
        port: 2282
      rpc:
        enabled: true
        port: 2283
  statsd:
    controller: statsd
    ports:
      graphite-web:
        port: 80
      graphite:
        port: 2003
      graphite-udp:
        port: 2003
        protocol: UDP
      statsd:
        port: 8125
        protocol: UDP
      statsd-admin:
        port: 8126

# for use with Kubernetes Gateway API
# route:
#   hubble:
#     enabled: true
#     kind: HTTPRoute
#     parentRefs:
#       - name: gateway
#         namespace: gateway-namespace
#     hostnames:
#       - hub.dtech.vision
#     rules:
#       - matches:
#         - path:
#             type: Prefix
#             value: /
#         backendRefs:
#           - kind: Service
#             name: hubble

persistence:
  # make sure this fits your storage setup
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 256Gi  # Adjust this value as needed

    # If you want to use hostPath, uncomment the following lines and comment out the above
    # enabled: true
    # type: hostPath
    # hostPath: /nvme0n1/farcaster-hub
    # size: 256Gi  # Still required even for hostPath
    # globalMounts:
    #  - path: /home/node/app/apps/hubble
